#Rectangular data

---

###Rectangular data is a two-dimensional matrix with rows denoting records (cases) and columns showing features (variables); data frame is the R and Python particular format. Unstructured data (such as text) must be handled and altered before being represented as a set of features in rectangular data. Rectangular data (like a spreadsheet) is the basic data structure for statistical and machine learning models.

---

####Key terms for rectangular data


*   Data frame - Rectangular data (like a spreadsheet) is the basic data structure for statistical and
machine learning models.
*   Feature - A column within a table is commonly referred to as a feature.

In [1]:
#importing and displaying a data frame

import pandas as pd

In [3]:
DataFrame = pd.read_csv('/content/tokenized_access_logs.csv')
DataFrame.head()

                                      Product  ...                                                url
0     adidas Brazuca 2017 Official Match Ball  ...  /department/fitness/category/baseball%20&%20so...
1       The North Face Women's Recon Backpack  ...  /department/fan%20shop/category/hunting%20&%20...
2      adidas Kids' RG III Mid Football Cleat  ...  /department/apparel/category/featured%20shops/...
3  Under Armour Men's Compression EV SL Slide  ...  /department/footwear/category/electronics/prod...
4                 Pelican Sunstream 100 Kayak  ...  /department/fan%20shop/category/water%20sports...

[5 rows x 8 columns]

#Non-rectangular data structures

##There are other data structures besides rectangular data. Time series data records successive measurements of the same variable. It is the raw material for statistical forecasting methods, and it is also a key component of the data produced by devices—the Internet of Things.